### ISSUE TITLE
Doubts regarding "Services in Code and how to use them in Flutter" blog post.

### ISSUE THREAD

**Issue by anoopeashok** [FilledStacks/stacked-example#12]
This is not an issue but some doubts regarding the blog posts.

- **FutureViewMode**l - Can we integrate different network requests in a single class?, for example, there are multiple network request should be called at different times, can we put in single Futureviewmodel class.

- in section **Share State / Functionality between ViewModels using Services** - can we get the same results by putting API request in corresponding view class instead of service class if data is shared only between two classes.

**Comment by FilledStacks** [comment]
@anoopeashok 

1. A FutureViewModel is used for a view that depends on the result from a Future. If you simply want to run a future when a button is pressed you'd just make a normal public function that returns a future and run that. 

```dart
class MyViewModelWithManyFutures extends BaseViewModel {

final _api = locator<Api>();

Future<Post> getAllPosts() => _api.getAllPosts();

Future<Post> createPost(Post post) => _api.createPost(post);

}

```
Then in the builder function you can just call that using model.createPost(Post(title: 'new post'));

2. No, there should be no business logic in views at any point. A view should contain the UI code only because it's main responsibility is to render the UI and manipulate it. 

You can however put it in a shared viewmodel implementation if you want to. The other viewmodels can then inherit from it. It'll be a bit harder to unit test but it works. I'd recommend using the a service instead regardless of how small it is because you're making a file with a single responsibility. It's easier for maintenance down the line.

**Comment by anoopeashok** [comment]
Thank you for the reply and architecture (it is awesome).

regarding future function, what if I want to run a future function on the build and another on a button click?. for example in a form at first I have to request some data from the network and on the submit click I have to send data to the network. 

or should I follow partialbuild example
